package sky.compiler;

import com.squareup.javapoet.ClassName;

/**
 * @author sky
 * @version 1.0 on 2017-10-30 下午7:32
 * @see SkyConsts
 */
public class SkyConsts {

	public static final ClassName	SKY_I_MODULE				= ClassName.get("sky.core.methodModule", "SKYIModule");

	public static final String		METHOD_LOAD_INTO			= "loadInto";

	public static final ClassName	SKY_I_MODULE_PARAM_MODEL	= ClassName.get("sky.core.methodModule", "SKYIMethodRun");

	public static final ClassName	SKY_I_MODULE_PARAM			= ClassName.get("android.util", "SparseArray");

	public static final ClassName	SKY_ANIMATION_AUTO_ID			= ClassName.get("sk", "AutoID");

	static final String				WARNING_TIPS				= "DO NOT EDIT THIS FILE!!! Sky TIPS~~";

	static final String				WARNING_TIPS_ID				= "组件化所有模块ID";

	static final String				FACADE_PACKAGE				= "sky.core";

	static final String				NAME_METHOD					= "_Method";

	static final ClassName			SKY_I_METHOD				= ClassName.get("sky.core.methodModule", "SKYIMethodRun");

	static final ClassName			SKY_HELPER					= ClassName.get(FACADE_PACKAGE, "SKYHelper");

	static final ClassName			SKY_L						= ClassName.get(FACADE_PACKAGE, "L");

	static final String				KEY_MODULE_NAME				= "SKY_MODULE_NAME";

	public static final String		NO_MODULE_NAME_TIPS			= "设置名称 'build.gradle', 这里添加:\n" + "android {\n" + "    defaultConfig {\n" + "        ...\n" + "        javaCompileOptions {\n"
			+ "            annotationProcessorOptions {\n" + "                arguments = [SKY_MODULE_NAME: project.getName()]\n" + "            }\n" + "        }\n" + "    }\n" + "}\n";
}
