package sk.compiler;

import com.squareup.javapoet.ClassName;

/**
 * @author sky
 * @version 1.0 on 2017-10-30 下午7:32
 * @see SkConsts
 */
class SkConsts {

	static final String		WARNING_TIPS		= "DO NOT EDIT THIS FILE!!! SK TIPS~~";

	static final String		FACADE_PACKAGE		= "sky.di";

	static final String		NAME_PROVIDER		= "_SKProvider";

	static final String		PROVIDER			= "Provider";

	static final String		INPUT_IMPL			= "SKInputImpl";

	static final String		NAME_INPUT			= "_SKInput";

	static final String		NAME_INPUT_IMPL		= "_SKInput_Impl";

	static final String		NAME_LIBRARY		= "_SKDILibrary";

	static final ClassName	SK_I_LAZY			= ClassName.get(FACADE_PACKAGE, "SKLazy");

	static final ClassName	SK_I_PROVIDER		= ClassName.get(FACADE_PACKAGE, "SKProvider");

	static final ClassName	MAP					= ClassName.get("java.util", "Map");

	static final ClassName	COLLECTIONS			= ClassName.get("java.util", "Collections");

	static final ClassName	SK_MAP				= ClassName.get(FACADE_PACKAGE, "SKMapBuilder");

	static final ClassName	SK_I_INPUT			= ClassName.get(FACADE_PACKAGE, "SKInput");

	static final ClassName	SK_PRECOND			= ClassName.get(FACADE_PACKAGE, "SKPreconditions");

	static final ClassName	SK_DC				= ClassName.get(FACADE_PACKAGE, "SKDoubleCheck");

	static final ClassName	SK_DI				= ClassName.get(FACADE_PACKAGE, "SKDispatchingInput");

	static final ClassName	SK_INTERFACE		= ClassName.get(FACADE_PACKAGE, "SKInitInterface");

	static final ClassName	SK_MANAGE_INTERFACE	= ClassName.get(FACADE_PACKAGE, "SKInputInterface");

	static final ClassName	SK_HELPER			= ClassName.get("sk", "SKHelper");

}