package sk.compiler;

import com.squareup.javapoet.ClassName;

/**
 * @author sky
 * @version 1.0 on 2017-10-30 下午7:32
 * @see SkConsts
 */
public class SkConsts {

	public static final String		WARNING_TIPS		= "DO NOT EDIT THIS FILE!!! SK TIPS~~";

	public static final String		FACADE_PACKAGE		= "sky.di";

	public static final ClassName	SK_I_LAZY			= ClassName.get(FACADE_PACKAGE, "SKLazy");

	public static final ClassName	SK_I_PROVIDER		= ClassName.get(FACADE_PACKAGE, "SKProvider");

	public static final ClassName	MAP					= ClassName.get("java.util", "Map");

	public static final ClassName	COLLECTIONS			= ClassName.get("java.util", "Collections");

	public static final ClassName	SK_MAP				= ClassName.get(FACADE_PACKAGE, "SKMapBuilder");

	public static final ClassName	SK_I_INPUT			= ClassName.get(FACADE_PACKAGE, "SKInput");

	public static final ClassName	SK_PRECOND			= ClassName.get(FACADE_PACKAGE, "SKPreconditions");

	public static final ClassName	SK_DC				= ClassName.get(FACADE_PACKAGE, "SKDoubleCheck");

	public static final ClassName	SK_DI				= ClassName.get(FACADE_PACKAGE, "SKDispatchingInput");

	public static final ClassName	SK_MANAGE_INTERFACE	= ClassName.get(FACADE_PACKAGE, "SKInputInterface");

	public static final ClassName	SK_HELPER			= ClassName.get("sk", "SKHelper");

}