package sk.modules;

import com.squareup.javapoet.ClassName;

/**
 * @author sky
 * @version 1.0 on 2017-10-30 下午7:32
 * @see SkConsts
 */
public class SkConsts {

	public static final ClassName	SK_I_MODULE				= ClassName.get("sk.methodModule", "SKIModule");

	public static final String		METHOD_LOAD_INTO			= "loadInto";

	public static final ClassName	SK_I_MODULE_RUN	= ClassName.get("sk.methodModule", "SKIMethodRun");

	public static final ClassName	SK_I_MODULE_PARAM			= ClassName.get("android.util", "SparseArray");

	static final String				WARNING_TIPS				= "DO NOT EDIT THIS FILE!!! Sky TIPS~~";

	static final String				FACADE_PACKAGE				= "sk";

	static final String				NAME_METHOD					= "_Method";

	static final ClassName			SK_HELPER					= ClassName.get(FACADE_PACKAGE, "SKHelper");

	static final ClassName			SK_L						= ClassName.get(FACADE_PACKAGE, "L");

	static final String				KEY_MODULE_NAME				= "SK_MODULE_NAME";

	public static final String		NO_MODULE_NAME_TIPS			= "设置名称 'build.gradle', 这里添加:\n" + "android {\n" + "    defaultConfig {\n" + "        ...\n" + "        javaCompileOptions {\n"
			+ "            annotationProcessorOptions {\n" + "                arguments = [SK_MODULE_NAME: project.getName()]\n" + "            }\n" + "        }\n" + "    }\n" + "}\n";
}
